import '../imports/startup/accounts-config.js';
import '../imports/ui/components/icon/icon';
import '../imports/ui/components/loading/loading.html';
import '../imports/ui/body.js';
import '../imports/i18n/i18n.js';
import 'bootstrap'
import '@popperjs/core'
import 'bootstrap/dist/css/bootstrap.css';
import '@fortawesome/fontawesome-free/js/all'
